name: Rust gRPC Service CI/CD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler libprotobuf-dev
          
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
          
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        
      - name: Run tests
        run: cargo test --verbose
        
      - name: Run clippy
        run: cargo clippy -- -D warnings
        
      - name: Run rustfmt
        continue-on-error: true
        run: cargo fmt --all -- --check
        
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Verify Docker Authentication
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          echo "Testing Docker Hub connectivity..."
          docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
          docker pull hello-world
          
      - name: Build and tag Docker image
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          docker build -t tembolo1284/rust-grpc-finance-server:latest .
          docker tag tembolo1284/rust-grpc-finance-server:latest tembolo1284/rust-grpc-finance-server:${{ github.sha }}
          
      - name: Push Docker image
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          docker push tembolo1284/rust-grpc-finance-server:latest
          docker push tembolo1284/rust-grpc-finance-server:${{ github.sha }}
